In [1]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import pylab as pl
#import seaborn as sns
#import statsmodels.api as sm

#%matplotlib inline
#sns.set(style='white', font_scale=0.9)

data_directory = os.path.join('.', 'cleaned_data') 

cleaned_accepted_data_path = os.path.join(data_directory, 'Cleaned_AcceptedLoanData.csv')
cleaned_rejected_data_path = os.path.join(data_directory, 'Cleaned_RejectedLoanData.csv')  

In [2]:
accepted_df = pd.read_csv(cleaned_accepted_data_path, low_memory=False, encoding='UTF-8')
print(accepted_df.info())

# Include selected columns.
accepted_df = accepted_df[['loan_amnt', 'mean_fico', 'dti', 'emp_length']]

# Add a column to indicate that this loan was accepted.
accepted_df['accepted'] = int(1)
print(accepted_df.info())
accepted_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131893 entries, 0 to 131892
Data columns (total 34 columns):
Unnamed: 0                    131893 non-null int64
loan_amnt                     131893 non-null float64
term                          131893 non-null object
int_rate                      131893 non-null float64
emp_length                    131893 non-null float64
home_ownership                131893 non-null object
annual_inc                    131893 non-null float64
verification_status           131893 non-null object
issue_d                       131893 non-null object
purpose                       131893 non-null object
dti                           131893 non-null float64
delinq_2yrs                   131893 non-null float64
earliest_cr_line              131893 non-null int64
inq_last_6mths                131893 non-null float64
mths_since_last_delinq        131893 non-null float64
pub_rec                       131893 non-null float64
revol_bal                     1318

loan_amnt      mean_fico            dti     emp_length  accepted
count  131893.000000  131893.000000  131893.000000  131893.000000  131893.0
mean    14770.019827     697.036977      18.242888       5.779071       1.0
std      8637.705924      30.746097       8.296326       3.724609       0.0
min       600.000000     622.000000       0.000000       0.000000       1.0
25%      8000.000000     672.000000      12.040000       2.000000       1.0
50%     13000.000000     692.000000      17.760000       6.000000       1.0
75%     20000.000000     712.000000      24.110000      10.000000       1.0
max     40000.000000     847.500000      46.520000      10.000000       1.0

In [3]:
# Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code,timestamp
rejected_df = pd.read_csv(cleaned_rejected_data_path, low_memory=False, encoding='UTF-8')
print(rejected_df.info())

# Include selected columns and rename them.
rejected_df = rejected_df[['loan_amnt', 'mean_fico', 'dti', 'emp_length']]

# Add a column to indicate that this loan was rejected.
rejected_df['accepted'] = int(0)

print(rejected_df.info())
rejected_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1107939 entries, 0 to 1107938
Data columns (total 5 columns):
Unnamed: 0    1107939 non-null int64
loan_amnt     1107939 non-null float64
mean_fico     467802 non-null float64
dti           1107939 non-null float64
emp_length    1107939 non-null float64
dtypes: float64(4), int64(1)
memory usage: 42.3 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1107939 entries, 0 to 1107938
Data columns (total 5 columns):
loan_amnt     1107939 non-null float64
mean_fico     467802 non-null float64
dti           1107939 non-null float64
emp_length    1107939 non-null float64
accepted      1107939 non-null int64
dtypes: float64(4), int64(1)
memory usage: 42.3 MB
None


loan_amnt      mean_fico           dti    emp_length   accepted
count  1.107939e+06  467802.000000  1.107939e+06  1.107939e+06  1107939.0
mean   1.342488e+04     623.460058  1.956712e+02  1.705757e+00        0.0
std    1.638031e+04     108.185247  9.295243e+03  1.883706e+00        0.0
min    0.000000e+00       0.000000 -1.000000e+00  0.000000e+00        0.0
25%    4.500000e+03     590.000000  6.100000e+00  1.000000e+00        0.0
50%    1.000000e+04     640.000000  1.802000e+01  1.000000e+00        0.0
75%    2.000000e+04     678.000000  3.360000e+01  1.000000e+00        0.0
max    1.400000e+06     990.000000  7.130330e+06  1.000000e+01        0.0

In [4]:
rejected_df['mean_fico'].fillna(0.0, inplace=True)

print(rejected_df.info())
rejected_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1107939 entries, 0 to 1107938
Data columns (total 5 columns):
loan_amnt     1107939 non-null float64
mean_fico     1107939 non-null float64
dti           1107939 non-null float64
emp_length    1107939 non-null float64
accepted      1107939 non-null int64
dtypes: float64(4), int64(1)
memory usage: 42.3 MB
None


loan_amnt     mean_fico           dti    emp_length   accepted
count  1.107939e+06  1.107939e+06  1.107939e+06  1.107939e+06  1107939.0
mean   1.342488e+04  2.632418e+02  1.956712e+02  1.705757e+00        0.0
std    1.638031e+04  3.158581e+02  9.295243e+03  1.883706e+00        0.0
min    0.000000e+00  0.000000e+00 -1.000000e+00  0.000000e+00        0.0
25%    4.500000e+03  0.000000e+00  6.100000e+00  1.000000e+00        0.0
50%    1.000000e+04  0.000000e+00  1.802000e+01  1.000000e+00        0.0
75%    2.000000e+04  6.240000e+02  3.360000e+01  1.000000e+00        0.0
max    1.400000e+06  9.900000e+02  7.130330e+06  1.000000e+01        0.0

In [5]:
print(accepted_df.shape)
print(rejected_df.shape)

(131893, 5)
(1107939, 5)


In [6]:
accepted_train_df, accepted_test_df = np.split(accepted_df.sample(frac=1), [int(0.5*len(accepted_df))])
print("accepted_train_df:")
print(accepted_train_df.shape)
print("accepted_test_df:")
print(accepted_test_df.shape)

accepted_train_df:
(65946, 5)
accepted_test_df:
(65947, 5)


In [7]:
rejected_train_df, rejected_test_df = np.split(rejected_df.sample(frac=1), [int(0.5*len(rejected_df))])
print("rejected_train_df:")
print(rejected_train_df.shape)
print("rejected_test_df:")
print(rejected_test_df.shape)

rejected_train_df:
(553969, 5)
rejected_test_df:
(553970, 5)


In [8]:
train_df = pd.concat([accepted_train_df, rejected_train_df])

# Shuffle the rows.
train_df = train_df.sample(frac=1).reset_index(drop=True)
print("train_df:")
print(train_df.shape)
print(train_df.head())

train_df:
(619915, 5)
   loan_amnt  mean_fico    dti  emp_length  accepted
0     1000.0      498.0  13.06         1.0         0
1    35000.0      726.0  39.36         1.0         0
2     2500.0      537.0  26.05         1.0         0
3     6000.0        0.0  39.69         0.0         0
4    12000.0      677.0  21.45         8.0         1


In [9]:
test_df = pd.concat([accepted_test_df, rejected_test_df])

# Shuffle the rows.
test_df = test_df.sample(frac=1).reset_index(drop=True)
print("test_df:")
print(test_df.shape)
print(test_df.head()) 

test_df:
(619917, 5)
   loan_amnt  mean_fico    dti  emp_length  accepted
0    15000.0      637.0  63.72         1.0         0
1     2000.0        0.0  -1.00         1.0         0
2    40000.0      686.0  12.55         1.0         0
3    20000.0      745.0  28.85         1.0         0
4     4000.0      720.0   9.00         1.0         0


In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import ensemble



In [11]:
#cols = ['loan_amt','mean_fico','dti','emp_length']   
#colsRes = ['accepted']

trainArr = train_df[['loan_amnt','mean_fico','dti','emp_length']]  #training array
trainRes = train_df[['accepted']] # training results

## Training

rf = ensemble.RandomForestClassifier(n_estimators=100) # initialize
rf.fit(trainArr, trainRes)


C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [13]:
test_df.isnull().values.any()
train_df.isnull().values.any()

False

In [14]:
## Testing!
# put the test data in the same format!
testArr = test_df[['loan_amnt','mean_fico','dti','emp_length']]
results = rf.predict(testArr)
# something I like to do is to add it back to the data frame, so I can compare side-by-side

testArr['predictions'] = results
testArr['accepted'] = test_df['accepted']

testArr.head()

loan_amnt  mean_fico    dti  emp_length  predictions  accepted
0    15000.0      637.0  63.72         1.0            0         0
1     2000.0        0.0  -1.00         1.0            0         0
2    40000.0      686.0  12.55         1.0            0         0
3    20000.0      745.0  28.85         1.0            0         0
4     4000.0      720.0   9.00         1.0            0         0

In [15]:
np.any(np.isnan(testArr))

False

In [16]:
np.all(np.isfinite(train_df))

True

In [17]:
from sklearn.metrics import classification_report,confusion_matrix
rf_confusion_mat = confusion_matrix(testArr['accepted'], testArr['predictions'])

print(rf_confusion_mat)

# Calculate by hand.
rf_accuracy = (rf_confusion_mat[0][0] + rf_confusion_mat[1][1]) / len(testArr)
print("Random Forest accuracy: " + str(rf_accuracy))

# Calculate using the Random Forest package - gives the same result.
#rf_acc = rf.score(testArr[['loan_amnt', 'mean_fico', 'dti', 'emp_length']], testArr[['accepted']])

[[544738   9232]
 [  7469  58478]]
Random Forest accuracy: 0.973059296648


In [18]:
##NEURAL NETWORK 
from sklearn.neural_network import MLPClassifier

In [19]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))

In [20]:
mlp.fit(train_df[['loan_amnt', 'mean_fico', 'dti', 'emp_length']], train_df['accepted'])

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(30, 30, 30), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [21]:
nn_predictions = mlp.predict(test_df[['loan_amnt', 'mean_fico', 'dti', 'emp_length']])

In [22]:
from sklearn.metrics import classification_report,confusion_matrix

nn_confusion_mat = confusion_matrix(test_df['accepted'], nn_predictions)
print(nn_confusion_mat)

nn_accuracy = (nn_confusion_mat[0][0] + nn_confusion_mat[1][1]) / len(testArr)
print("Neural network accuracy: " + str(nn_accuracy))

[[543905  10065]
 [ 31303  34644]]
Neural network accuracy: 0.933268485942


In [23]:
print(classification_report(test_df['accepted'], nn_predictions))

             precision    recall  f1-score   support

          0       0.95      0.98      0.96    553970
          1       0.77      0.53      0.63     65947

avg / total       0.93      0.93      0.93    619917



In [24]:
from sklearn.metrics import roc_curve, auc


In [29]:
# SVM (support vector machines) also known as SVN (support vector networks).

from sklearn import svm

clf = svm.SVC()
clf.fit(train_df[['loan_amnt', 'mean_fico', 'dti', 'emp_length']][:10000], train_df['accepted'][:10000]) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [31]:
# Predict results.
svm_predictions = clf.predict(test_df[['loan_amnt', 'mean_fico', 'dti', 'emp_length']])

In [32]:
svm_confusion_mat = confusion_matrix(test_df['accepted'], svm_predictions)
print(svm_confusion_mat)

svm_accuracy = (svm_confusion_mat[0][0] + svm_confusion_mat[1][1]) / len(svm_predictions)
print("Support vector machine accuracy: " + str(svm_accuracy))

[[553698    272]
 [ 64579   1368]]
Support vector machine accuracy: 0.895387608341
